#load
        "fsstrings.fs"
        "unicode.fs"
        "adapters.fs"
        // "../../assemblyinfo/assemblyinfo.FSharp.Compiler.Service.dll.fs"
        // "../../assemblyinfo/assemblyinfo.shared.fs"
        "../FSharp.Compiler.Service/FSComp.fs"
        "../FSharp.Compiler.Service/FSIstrings.fs"
        // "../../utils/reshapedreflection.fs"
        "../../utils/sformat.fsi"
        "../../utils/sformat.fs"
        // "../sr.fsi"
        // "../sr.fs"
        "../../utils/prim-lexing.fsi"
        "../../utils/prim-lexing.fs"
        "../../utils/prim-parsing.fsi"
        "../../utils/prim-parsing.fs"
        "../../utils/ResizeArray.fsi"
        "../../utils/ResizeArray.fs"
        "../../utils/HashMultiMap.fsi"
        "../../utils/HashMultiMap.fs"
        "../../utils/EditDistance.fs"
        "../../utils/TaggedCollections.fsi"
        "../../utils/TaggedCollections.fs"
        "../QueueList.fs"
        "../../absil/ildiag.fsi"
        "../../absil/ildiag.fs"
        "../../absil/illib.fs"
        "../../utils/filename.fsi"
        "../../utils/filename.fs"
        "../../absil/bytes.fsi"
        "../../absil/bytes.fs"
        "../../absil/zmap.fsi"
        "../../absil/zmap.fs"
        "../../absil/zset.fsi"
        "../../absil/zset.fs"
        "../lib.fs"
        "../InternalCollections.fsi"
        "../InternalCollections.fs"
        "../rational.fsi"
        "../rational.fs"
        "../range.fsi"
        "../range.fs"
        "../ErrorLogger.fs"
        "../ErrorResolutionHints.fs"
        "../ReferenceResolver.fs"
        "../../absil/il.fsi"
        "../../absil/il.fs"
        "../../absil/ilx.fsi"
        "../../absil/ilx.fs"
        // "../../absil/ilascii.fsi"
        // "../../absil/ilascii.fs"
        // "../../absil/ilprint.fsi"
        // "../../absil/ilprint.fs"
        "../../absil/ilmorph.fsi"
        "../../absil/ilmorph.fs"
        // "../../absil/ilsign.fs"
        // "../../absil/ilsupp.fsi"
        // "../../absil/ilsupp.fs"
        // "ilpars.fs"
        // "illex.fs"
        "../../absil/ilbinary.fsi"
        "../../absil/ilbinary.fs"
        "../../absil/ilread.fsi"
        "../../absil/ilread.fs"
        // "../../absil/ilwritepdb.fsi"
        // "../../absil/ilwritepdb.fs"
        // "../../absil/ilwrite.fsi"
        // "../../absil/ilwrite.fs"
        // "../../absil/ilreflect.fs"
        // "../../utils/CompilerLocationUtils.fs"
        "../PrettyNaming.fs"
        "../../ilx/ilxsettings.fs"
        "../../ilx/EraseClosures.fsi"
        "../../ilx/EraseClosures.fs"
        "../../ilx/EraseUnions.fsi"
        "../../ilx/EraseUnions.fs"
        "../UnicodeLexing.fsi"
        "../UnicodeLexing.fs"
        "../layout.fsi"
        "../layout.fs"
        "../ast.fs"
        "../FSharp.Compiler.Service/pppars.fs"
        "../FSharp.Compiler.Service/pars.fs"
        "../lexhelp.fsi"
        "../lexhelp.fs"
        "../FSharp.Compiler.Service/pplex.fs"
        "../FSharp.Compiler.Service/lex.fs"
        "../LexFilter.fs"
        // "../tainted.fsi"
        // "../tainted.fs"
        // "../ExtensionTyping.fsi"
        // "../ExtensionTyping.fs"
        "../QuotationPickler.fsi"
        "../QuotationPickler.fs"
        "../tast.fs"
        "../TcGlobals.fs"
        "../TastOps.fsi"
        "../TastOps.fs"
        "../TastPickle.fsi"
        "../TastPickle.fs"
        "../import.fsi"
        "../import.fs"
        "../infos.fs"
        "../AccessibilityLogic.fs"
        "../AttributeChecking.fs"
        "../InfoReader.fs"
        "../NicePrint.fs"
        "../AugmentWithHashCompare.fsi"
        "../AugmentWithHashCompare.fs"
        "../NameResolution.fsi"
        "../NameResolution.fs"
        "../TypeRelations.fs"
        "../SignatureConformance.fs"
        "../MethodOverrides.fs"
        "../MethodCalls.fs"
        "../PatternMatchCompilation.fsi"
        "../PatternMatchCompilation.fs"
        "../ConstraintSolver.fsi"
        "../ConstraintSolver.fs"
        "../CheckFormatStrings.fsi"
        "../CheckFormatStrings.fs"
        "../FindUnsolved.fs"
        "../QuotationTranslator.fsi"
        "../QuotationTranslator.fs"
        "../PostInferenceChecks.fsi"
        "../PostInferenceChecks.fs"
        "../TypeChecker.fsi"
        "../TypeChecker.fs"
        "../Optimizer.fsi"
        "../Optimizer.fs"
        // "../DetupleArgs.fsi"
        // "../DetupleArgs.fs"
        // "../InnerLambdasToTopLevelFuncs.fsi"
        // "../InnerLambdasToTopLevelFuncs.fs"
        // "../LowerCallsAndSeqs.fs"
        // "../autobox.fs"
        // "../IlxGen.fsi"
        // "../IlxGen.fs"
        // "../CompileOps.fsi"
        "../CompileOps.fs"
        // "../CompileOptions.fsi"
        // "../CompileOptions.fs"
        // "../fsc.fsi"
        // "../fsc.fs"
        "../vs/IncrementalBuild.fsi"
        "../vs/IncrementalBuild.fs"
        "../vs/Reactor.fsi"
        "../vs/Reactor.fs"
        "../vs/ServiceConstants.fs"
        "../vs/ServiceDeclarations.fsi"
        "../vs/ServiceDeclarations.fs"
        "../vs/Symbols.fsi"
        "../vs/Symbols.fs"
        "../vs/Exprs.fsi"
        "../vs/Exprs.fs"
        "../vs/ServiceLexing.fsi"
        "../vs/ServiceLexing.fs"
        "../vs/ServiceParseTreeWalk.fs"
        "../vs/ServiceNavigation.fsi"
        "../vs/ServiceNavigation.fs"
        "../vs/ServiceParamInfoLocations.fsi"
        "../vs/ServiceParamInfoLocations.fs"
        "../vs/ServiceUntypedParse.fsi"
        "../vs/ServiceUntypedParse.fs"
        // "../../utils/reshapedmsbuild.fs"
        // "../MSBuildReferenceResolver.fs"
        "../vs/service.fsi"
        "../vs/service.fs"
        // "../vs/SimpleServices.fsi"
        // "../vs/SimpleServices.fs"
        // "../fsi/fsi.fsi"
        // "../fsi/fsi.fs"
        "service_shim.fs"
