// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyVersionAttribute("11.0.4")>]
[<assembly: AssemblyFileVersionAttribute("11.0.4")>]
[<assembly: AssemblyInformationalVersionAttribute("11.0.4")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyVersion = "11.0.4"
    let [<Literal>] AssemblyFileVersion = "11.0.4"
    let [<Literal>] AssemblyInformationalVersion = "11.0.4"
